# Generated by Django 6.0.5 on 2026-07-03 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='block',
            field=models.CharField(blank=True, choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D'), ('E', 'Block E'), ('F', 'Block F')], max_length=10),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='door_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='floor',
            field=models.CharField(blank=True, choices=[('Ground', 'Ground Floor'), ('1st', '1st Floor'), ('2nd', '2nd Floor'), ('3rd', '3rd Floor'), ('4th', '4th Floor'), ('5th', '5th Floor')], max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='office_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Admin', 'Administration'), ('Engineering', 'Engineering'), ('Procurement', 'Procurement'), ('Legal', 'Legal'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Security', 'Security')], max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Admin', 'Administration'), ('Engineering', 'Engineering'), ('Procurement', 'Procurement'), ('Legal', 'Legal'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Security', 'Security')], max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Admin', 'Administration'), ('Engineering', 'Engineering'), ('Procurement', 'Procurement'), ('Legal', 'Legal'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Security', 'Security')], max_length=100)),
                ('block', models.CharField(blank=True, choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D'), ('E', 'Block E'), ('F', 'Block F')], max_length=10)),
                ('floor', models.CharField(blank=True, choices=[('Ground', 'Ground Floor'), ('1st', '1st Floor'), ('2nd', '2nd Floor'), ('3rd', '3rd Floor'), ('4th', '4th Floor'), ('5th', '5th Floor')], max_length=20)),
                ('office_name', models.CharField(blank=True, max_length=100)),
                ('door_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
