# Generated by Django 6.0.5 on 2026-07-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_maintenanceticket_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
    ]
