# Generated by Django 6.0.5 on 2026-07-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Administration Police', 'Administration Police'), ('Labour', 'Labour'), ('Procurement', 'Procurement'), ('TSE', 'TSE'), ('Naccada', 'Naccada'), ('Regional Commissioner', 'Regional Commissioner'), ('County commissioner', 'County commissioner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Administration Police', 'Administration Police'), ('Labour', 'Labour'), ('Procurement', 'Procurement'), ('TSE', 'TSE'), ('Naccada', 'Naccada'), ('Regional Commissioner', 'Regional Commissioner'), ('County commissioner', 'County commissioner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Administration Police', 'Administration Police'), ('Labour', 'Labour'), ('Procurement', 'Procurement'), ('TSE', 'TSE'), ('Naccada', 'Naccada'), ('Regional Commissioner', 'Regional Commissioner'), ('County commissioner', 'County commissioner')], max_length=100),
        ),
    ]
