# Generated by Django 6.0.5 on 2026-07-13 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='ticket_type',
            field=models.CharField(choices=[('Hardware', 'Hardware Issue'), ('Network', 'Network / Connectivity Issue')], default='Hardware', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='department',
            field=models.CharField(blank=True, choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Administration Police', 'Administration Police'), ('Labour', 'Labour'), ('Procurement', 'Procurement'), ('TSE', 'TSE'), ('Naccada', 'Naccada'), ('Regional Commissioner', 'Regional Commissioner'), ('County commissioner', 'County commissioner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
